### ISSUE TITLE
Display of password incorrect

### ISSUE THREAD

**Issue by PuuTheBear** [vergecurrency/MyVergies#15]
**To Reproduce**
1. Create new wallet
2. Set password for wallet

**Expected behavior**
Special chars should not light up green

**Screenshots**
![grafik](https://user-images.githubusercontent.com/58558820/82832078-6d1dda00-9eba-11ea-9c50-3c451175eb4d.png)

**Comment by SwenVanZanten** [comment]
We will have to change the label, cause the regex used is also being used on iOS 😅 
Otherwise there would be a compatibility issue.

**Comment by SwenVanZanten** [comment]
Fix in 20e432b98851686d13d9f0d370549d490cab7e20
