### ISSUE TITLE
Request: Design suggestions (Verge branding)

### ISSUE THREAD

**Issue by marpme** [vergecurrency/MyVergies#32]
The shapes are excellent! But I would add is a bit of more “verge” blue to the frame. The greys remind me of win98. 
Icons are sick, it’s just the surroundings that needs either some blue or some shades or some transparency to make it look slicker. What ya think?

Something along those lines:

![image](https://user-images.githubusercontent.com/7430964/88946405-83b42900-d28f-11ea-9a12-a1746de8a290.png)

##### Source: 
https://twitter.com/SteveMa11163497/status/1288867690782785536?s=20
##### Twitter: 
@SteveMa11163497

**Comment by SwenVanZanten** [comment]
This isn't a "verge" wallet, this is my wallet. My branding, my design 😉 

Lol the windows pics didn't help at all. 

Closing this
