### ISSUE TITLE
AppImage fails to run, uncaught exception

### ISSUE THREAD

**Issue by probonopd** [vergecurrency/MyVergies#39]
**Describe the bug**
AppImage fails to run, uncaught exception

**To Reproduce**
1. Run Xubuntu 18.04
2. Try to run the AppImage

**Expected behavior**
Runs

**Screenshots**
![](https://raw.githubusercontent.com/AppImage/appimage.github.io/5357b59a8ea6efc3b0fc3ec3454c79d9036cfbf1/database/MyVergies/screenshot.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Version: 18.04

**Additional context**
AppImages are read-only. Trying to chmod something within the AppImage at runtime will fail. Just like it would fail if the application was installed at e.g., `/usr/bin` and then run by a regular user.

If you need to write, then you need to write somewhere within `$HOME`.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2248

**Comment by SwenVanZanten** [comment]
Cool is fixed in v0.6 by copying the Tor bin files to app directory
