### ISSUE TITLE
Integration of Tor proxying

### ISSUE THREAD

**Issue by marpme** [vergecurrency/MyVergies#4]
### Synopsis

Having a tor connection will enable the wallet client to securely talk via open internet connections to our recommended wallet servers that are handling light clients.

### Tech Requirements

* Each and every operating system should get the latest tor executable shipped within the wallet:
  * Windows 10+
  * Ubuntu
  * MacOS
* We'll check the checksum of the executable against a hard-coded one. (probably SHA512) to ensure security
* It should be put on by default and should automatically setup itself to connected

**Comment by SwenVanZanten** [comment]
Basic functionality was added in #9 
There is somethings which still needs to be build.
- [ ] an indication of the TOR status
- [ ] an option to turn of TOR
- [ ] the possibility to see the TOR circuit or/and see your exit node "location" and IP
- [ ] verify Linux development and production implementation works

**Comment by SwenVanZanten** [comment]
Issues created, will close this one 🙏
