### ISSUE TITLE
never received transfer 

### ISSUE THREAD

**Issue by bummed5** [vergecurrency/MyVergies#45]
treansfered from binance to a new xvg wallet on myvergies never went trhough

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by justinvforvendetta** [comment]
@bummed5 seems unlikely but im guessing it finally worked for you.
