### ISSUE TITLE
Balance not reflected in MyVergies

### ISSUE THREAD

**Issue by Jt0th3s** [vergecurrency/MyVergies#46]
**Describe the bug**
I processed a transfer from Binance to a new MyVergies wallet address today. The transfer is recorded / confirmed in the Verge Blockchain, showing up at the right address. However my wallet on my Windows MyVergies does not reflect the balance.
I double checked the address for correctness multiple times.

**Expected behavior**
I expected for the balance to be reflected in MyVergies after it has been confirmed in the blockhain.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Firefox

**Comment by NikitaSheglov01** [comment]
Does anyone know how to restore the verge wallet through the seed phrase? lost wallet.dat file, don't understand how to get wallet back?

**Comment by justinvforvendetta** [comment]
@NikitaSheglov01 this wallet "myvergies" doesnt use a wallet.dat as far as i know. i think you are thinking of our core wallet (https://github.com/vergecurrency/verge)

**Comment by justinvforvendetta** [comment]
@Jt0th3s are you sure the myvergies wallet is connected?

**Comment by justinvforvendetta** [comment]
@Jt0th3s @NikitaSheglov01 let us know if you figure anything out, otherwise this is closed for lack of response.
